# Generated by Django 4.1.5 on 2023-02-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0013_alter_todolist_action_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todolist",
            name="action_date",
            field=models.DateField(
                auto_now_add=True, verbose_name="Date of completion"
            ),
        ),
    ]
