# Generated by Django 4.1.5 on 2023-02-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0016_alter_todolist_action_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="todolist",
            name="detailed_description",
            field=models.TextField(
                help_text="Enter a detailed description",
                max_length=2000,
                null=True,
                verbose_name="Detailed description",
            ),
        ),
    ]
