# Generated by Django 4.1.5 on 2023-02-22 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0017_todolist_detailed_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todolist", options={"verbose_name_plural": "To-Do List"},
        ),
    ]
