# Generated by Django 4.1.5 on 2023-02-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0018_alter_todolist_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="todolist",
            name="deleted_date",
            field=models.DateTimeField(
                default=None, null=True, verbose_name="Date of deletion"
            ),
        ),
        migrations.AddField(
            model_name="todolist",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Deleted"),
        ),
    ]
