# Generated by Django 4.1.5 on 2023-02-22 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0019_todolist_deleted_date_todolist_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todolist",
            name="action_date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 2, 22, 19, 15, 59, 210859, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Date of completion",
            ),
        ),
    ]
