# Generated by Django 4.1.5 on 2023-02-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0022_alter_todolist_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todolist",
            name="detailed_description",
            field=models.TextField(
                blank=True,
                max_length=2000,
                null=True,
                verbose_name="Detailed description",
            ),
        ),
    ]
